### ISSUE TITLE
Design: my profile

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#381]
## Description

- [ ] set avatar ( image upload is needed for this)
- [x] show all playground you joined
- [x] edit password
- [ ] edit e-mail
- [x] unroll account (soft delete)
- [ ] delete account 

## Wireframe
![Untitled Diagram (2)](https://user-images.githubusercontent.com/10818702/58080810-2e24bc80-7bb4-11e9-9b4b-16f9f5f25933.png)

**Comment by dimitri** [comment]
I don't think you wanted to mention me here?

**Comment by dimitriirtimid** [comment]
@maxvisser Eeeek! edit e-mail is not going to work as we are using it as kind-of unique key to the account (just as the username by the way). If you really really want it I can check for the impact of modifying this.

**Comment by dimitriirtimid** [comment]
And what is the difference between unroll account and delete account?

**Comment by maxvisser** [comment]
You explained it to me the difference between 'uitschrijven' and complete deletion right?

**Comment by maxvisser** [comment]
Edit mail is not a prio right now

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/469

Notes:
- We need to make relations between a user and playgrounds he joined because for now to match user and playground we could only go through all playgrounds and find in all its volunteers, it causes too many operations
- We need user fields that: will indicate that a user allowed notifications; link to userAvatar and a way to upload it. Also we need requirements for this avatar (resolutions, max kb, format)
- We need functions that: will remove a user account; check current password and change new one; change username and email
- For an actie in the list of acties we need some way to get the image of the playground - should it be some static image like now or it should be uploaded somehow by creator of the playground

**Comment by maxvisser** [comment]
I think anand is busy with image upload for playgrounds, I will make an issue about this

**Comment by dimitriirtimid** [comment]
@maxvisser @KarafiziArtur @AnandAili 

Interesting issue :) . , I have a number of comments:
- set avatar: Anand is currently working on this (picture upload), so it can be connected when he is done
- show all playgrounds you joined: I just discussed this with Anand. We will extend the GET_USER_PROFILE query to return a list of initiatives that the user is member of. To be picked up later this week I guess.
- edit password: We do not do this yet, but it is possible with Cognito. I will implement this after I am done with the authentication refactor. I see that Arthur has already done work on this. I hope it does not clash too much ;)
- edit username and password: It is not possible to (easily) implement this at this moment. I will discuss with Max separately. For now I propose to make these read-only fields.
- unroll/delete account: Should just be one 'uitschrijven' action that triggers the same functionality as currently in the user menu. @maxvisser about the 'fully deleting account' : I think what I meant is that to user can ask to be forgotten. We do not want to provide this as a self-service options, because if a user has misbehaved we need to retain the data, at least for a while. So forgetting a user should be a maintenance function.

**Comment by maxvisser** [comment]
Great comment; I agree completely, already knew about some of the limitations. I think we can work towards implementing all your comments @KarafiziArtur

**Comment by dimitriirtimid** [comment]
Update after PR https://github.com/local-motion/onboarding-web/pull/481
show all playgrounds you joined: -> implemented in PR
edit password: -> implemented in PR
