### ISSUE TITLE
Internet Explorer registration of account

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#424]
## Description
I got a message from a beta tester, she works on windows 7 with Internet Explorer 11 as her browser; she got stuck in the registration process of an account, a blank screen

## task
- [x] reproduce issue
- [ ] fix issue

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/501

**Comment by dimitriirtimid** [comment]
Windows 7 / IE11 are out of support and therefore getting dangerous to use. Also I have no facilities to test the application on this platform. Users should just upgrade (if not to Windows10 then at least to a current browser, Chrome for instance).
So instead of fixing this issue I propose to implement issue #190  (Unsupported browser message)
